blank_issues_enabled: false
contact_links:
  - name: Support Center
    url: https://github.com/Termix-SSH/Support/issues
    about: Report any feature requests or bugs in the support center
  - name: Discord
    url: https://discord.gg/jVQGdvHDrf
    about: Official Termix Discord server for general discussion and quick support
